<a href="https://colab.research.google.com/github/pabasara404/smile-detect_model/blob/main/Smile_detection_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from PIL import Image
import os
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

directory ="/content/drive/MyDrive/Datasets/Datasets/smiles_dataset/training_set/"

pixel_intensities = []
labels = []

for filename in os.listdir(directory):
  image = Image.open(directory+filename).convert('1')
  pixel_intensities.append(list(image.getdata()))
  if filename[0:5]=='happy':
    labels.append([1,0])
  elif filename[0:3]=='sad':
    labels.append([0,1])

pixel_intensities = np.array(pixel_intensities)
labels = np.array(labels)
# print(labels.shape)

pixel_intensities = pixel_intensities /255.0
print(pixel_intensities)

model = Sequential()
model.add(Dense(1024, input_dim=1024, activation='relu'))
model.add(Dense(512, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(2, activation='softmax'))

optimizer = Adam(lr=0.005)
model.compile(loss='categorical_crossentropy',
               optimizer=optimizer,
               metrics=['accuracy'])

model.fit(pixel_intensities, labels, epochs=1000, batch_size=20,verbose=2)



[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Epoch 1/1000


/usr/local/lib/python3.10/dist-packages/keras/optimizers/legacy/adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


1/1 - 1s - loss: 0.8140 - accuracy: 0.5000 - 555ms/epoch - 555ms/step
Epoch 2/1000
1/1 - 0s - loss: 47.3171 - accuracy: 0.5000 - 19ms/epoch - 19ms/step
Epoch 3/1000
1/1 - 0s - loss: 4.3290 - accuracy: 0.5000 - 19ms/epoch - 19ms/step
Epoch 4/1000
1/1 - 0s - loss: 5.2400 - accuracy: 0.5000 - 21ms/epoch - 21ms/step
Epoch 5/1000
1/1 - 0s - loss: 0.8537 - accuracy: 0.5000 - 21ms/epoch - 21ms/step
Epoch 6/1000
1/1 - 0s - loss: 1.5813 - accuracy: 0.5000 - 21ms/epoch - 21ms/step
Epoch 7/1000
1/1 - 0s - loss: 3.0762 - accuracy: 0.5000 - 21ms/epoch - 21ms/step
Epoch 8/1000
1/1 - 0s - loss: 1.0664 - accuracy: 0.5000 - 20ms/epoch - 20ms/step
Epoch 9/1000
1/1 - 0s - loss: 3.6780 - accuracy: 0.5000 - 26ms/epoch - 26ms/step
Epoch 10/1000
1/1 - 0s - loss: 2.5359 - accuracy: 0.5000 - 19ms/epoch - 19ms/step
Epoch 11/1000
1/1 - 0s - loss: 2.1402 - accuracy: 0.5000 - 19ms/epoch - 19ms/step
Epoch 12/1000
1/1 - 0s - loss: 1.7290 - accuracy: 0.5000 - 20ms/epoch - 20ms/step
Epoch 13/1000
1/1 - 0s - loss: 1.08

In [14]:
test_pixel_intensities =[]
test_image1=Image.open('/content/drive/MyDrive/Datasets/Datasets/smiles_dataset/test_set/happy_test.png').convert('1')
test_pixel_intensities.append(list(test_image1.getdata()))

test_pixel_intensities = np.array(test_pixel_intensities)/255.0
print(model.predict(test_pixel_intensities).round())

1/1 [==============================] - 0s 72ms/step
[[1. 0.]]
